### ISSUE TITLE
作者你好，请问代码是还没更新完吗

### ISSUE THREAD

**Issue by 1632325673** [04RR/MedSRGAN#1]

**Comment by 04RR** [comment]
Hey!
The code is mostly done, I just have a few more features to add.

**Comment by 1632325673** [comment]
OK, thank you for your reply.&nbsp;
When can the update be completed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "04RR/MedSRGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 凌晨2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [04RR/MedSRGAN] 作者你好，请问代码是还没更新完吗 (#1)





 
Hey!
 The code is mostly done, I just have a few more features to add.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
